### ISSUE TITLE
AttributeError: 'list' object has no attribute 'clear'

### ISSUE THREAD

**Issue by mikeporetti** [jchanvfx/NodeGraphQt#172]
Just trying to run some example code that comes with the download

Traceback (most recent call last):
  File "P:\appconfig\common\gui\NodeGraphQt-master\NodeGraphQt\base\graph.py", line 223, in _toggle_tab_search
    self._viewer.tab_search_set_nodes(self._node_factory.names)
  File "P:\appconfig\common\gui\NodeGraphQt-master\NodeGraphQt\widgets\viewer.py", line 734, in tab_search_set_nodes
    self._search_widget.set_nodes(nodes)
  File "P:\appconfig\common\gui\NodeGraphQt-master\NodeGraphQt\widgets\tab_search.py", line 273, in set_nodes
    self._clear_actions()
  File "P:\appconfig\common\gui\NodeGraphQt-master\NodeGraphQt\widgets\tab_search.py", line 186, in _clear_actions
    self._searched_actions.clear()
AttributeError: 'list' object has no attribute 'clear'

**Comment by mikeporetti** [comment]
im running on python 2.7 is it no longer compatable?

**Comment by mikeporetti** [comment]
commenting out that line seems to fix it, but i have no idea at what cost

**Comment by mikeporetti** [comment]
I also really just want to thank you for this open source code.  What you have done is amazing.

**Comment by jchanvfx** [comment]
addressed in pull request #192
