### ISSUE TITLE
Distribution with `PyInstaller` / `Nuitka`

### ISSUE THREAD

**Issue by tamasmuncsan** [jchanvfx/NodeGraphQt#204]
I'm using `v0.1.1` of `NodeGraphQt` in my app.

I've tried to make an executable out of my source code using `Pyinstaller` / `Nuitka`, but both of them give the  following error after running the build executable:

Nuitka: 
```sh
Traceback (most recent call last):
  File "/Users/<>/Private/ai-viewer/./main.dist/main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/<>/Private/ai-viewer/./main.dist/NodeGraphQt/__init__.py", line 77, in <module NodeGraphQt>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/tamas/Private/ai-viewer/./main.dist/Qt.py", line 1919, in <module Qt>
  File "/Users/tamas/Private/ai-viewer/./main.dist/Qt.py", line 1897, in _install
AttributeError: partially initialized module 'Qt' has no attribute 'QtGui' (most likely due to a circular import)
```

PyInstaller:
```sh
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "NodeGraphQt/__init__.py", line 77, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "Qt.py", line 1919, in <module>
  File "Qt.py", line 1897, in _install
AttributeError: partially initialized module 'Qt' has no attribute 'QtGui' (most likely due to a circular import)
[74601] Failed to execute script main
```

Any help would be appreciated, maybe I am missing some hidden import...

**Comment by dangerstudios** [comment]
Try this, worked for me:
https://github.com/brentvollebregt/auto-py-to-exe
