### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by GinnerskovRIF** [jchanvfx/NodeGraphQt#212]
This project looks very nice. In fear of asking the obvious, how do I try it out? How do I install?

I've cloned the repo, done a `pip install .`, but upon running e.g. `python example.py` I get the following error message:

```
Traceback (most recent call last):
  File "/home/ginner/Development/testing/nodegraphqt/NodeGraphQt/example.py", line 7, in <module>
    from NodeGraphQt import (NodeGraph,
  File "/home/ginner/.pyenv/versions/3.9.5/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/ginner/Development/testing/nodegraphqt/NodeGraphQt/NodeGraphQt/__init__.py", line 76, in <module>
    from .base.graph import NodeGraph, SubGraph
  File "/home/ginner/.pyenv/versions/3.9.5/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/ginner/Development/testing/nodegraphqt/NodeGraphQt/NodeGraphQt/base/graph.py", line 16, in <module>
    from .menu import NodeGraphMenu, NodesMenu
  File "/home/ginner/.pyenv/versions/3.9.5/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/ginner/Development/testing/nodegraphqt/NodeGraphQt/NodeGraphQt/base/menu.py", line 7, in <module>
    from ..widgets.actions import BaseMenu, GraphAction, NodeAction
  File "/home/ginner/.pyenv/versions/3.9.5/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/ginner/Development/testing/nodegraphqt/NodeGraphQt/NodeGraphQt/widgets/actions.py", line 2, in <module>
    from .. import QtCore, QtWidgets
ImportError: cannot import name 'QtCore' from partially initialized module 'NodeGraphQt' (most likely due to a circular import) (/home/ginner/Development/testing/nodegraphqt/NodeGraphQt/NodeGraphQt/__init__.py)
```

Thanks a bunch!

**Comment by ArnoChenFx** [comment]
Add  line "**from Qt import QtCore, QtWidgets, QtGui**" to "**NodeGraphQt/__init__.py**"  can fix it.

**Comment by GinnerskovRIF** [comment]
Thank you, that worked!
