### ISSUE TITLE
Installing NodeGraphQt requires Qt.py to be installed

### ISSUE THREAD

**Issue by Martmists-GH** [jchanvfx/NodeGraphQt#269]
This makes setting up applications depending on NodeGraphQt difficult, as a crash happens in setup.py:

```
Processing /home/mart/git/kaudio-python
  Preparing metadata (setup.py) ... done
Collecting NodeGraphQt@ git+https://github.com/jchanvfx/NodeGraphQt.git@227594c907bd9abad88bc1d859452fad18352f5d#egg=NodeGraphQt
  Cloning https://github.com/jchanvfx/NodeGraphQt.git (to revision 227594c907bd9abad88bc1d859452fad18352f5d) to /tmp/pip-install-mf941_v1/nodegraphqt_ebde16ba40fc425ca40997385d9a89f0
  Running command git clone --filter=blob:none --quiet https://github.com/jchanvfx/NodeGraphQt.git /tmp/pip-install-mf941_v1/nodegraphqt_ebde16ba40fc425ca40997385d9a89f0
  Running command git rev-parse -q --verify 'sha^227594c907bd9abad88bc1d859452fad18352f5d'
  Running command git fetch -q https://github.com/jchanvfx/NodeGraphQt.git 227594c907bd9abad88bc1d859452fad18352f5d
  Resolved https://github.com/jchanvfx/NodeGraphQt.git to commit 227594c907bd9abad88bc1d859452fad18352f5d
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-mf941_v1/nodegraphqt_ebde16ba40fc425ca40997385d9a89f0/setup.py", line 5, in <module>
          from NodeGraphQt import pkg_info
        File "/tmp/pip-install-mf941_v1/nodegraphqt_ebde16ba40fc425ca40997385d9a89f0/NodeGraphQt/__init__.py", line 79, in <module>
          from .base.graph import NodeGraph, SubGraph
        File "/tmp/pip-install-mf941_v1/nodegraphqt_ebde16ba40fc425ca40997385d9a89f0/NodeGraphQt/base/graph.py", line 8, in <module>
          from Qt import QtCore, QtWidgets
      ModuleNotFoundError: No module named 'Qt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Oddly enough this import is not satisfied even when PySide2 is already installed.

**Comment by tristanpoland** [comment]
Is this still an issue? I am having some issues getting this to play nice with PyQt5.

**Comment by Zelfior** [comment]
@tristanpoland , it is not working with the module pyqt but with qt.py module. It is confusing i agree. If you run the command python -m pip install -e path_to_nodegraphqt, it will install the required dependancies. And should work immediatly

**Comment by tristanpoland** [comment]
@Zelfior Thanks, that fixed it for me. The naming conventions in Python libraries in particular seem to be quite confusing, I appreciate the help!
