### ISSUE TITLE
Can not start new project from scratch v0.6.12

### ISSUE THREAD

**Issue by thanhtham010891** [jchanvfx/NodeGraphQt#365]
There are an error
`Traceback (most recent call last):
  File "C:\Users\VHcom\Desktop\graph-qt\main.py", line 105, in <module>
    node_graph = NodeGraph()
                 ^^^^^^^^^^^
  File "C:\Users\VHcom\Desktop\graph-qt\venv\Lib\site-packages\NodeGraphQt\base\graph.py", line 157, in __init__
    kwargs.get('viewer') or NodeViewer(undo_stack=self._undo_stack)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VHcom\Desktop\graph-qt\venv\Lib\site-packages\NodeGraphQt\widgets\viewer.py", line 113, in __init__
    self._LIVE_PIPE = LivePipeItem()
                      ^^^^^^^^^^^^^^
  File "C:\Users\VHcom\Desktop\graph-qt\venv\Lib\site-packages\NodeGraphQt\qgraphics\pipe.py", line 553, in __init__
    super(LivePipeItem, self).__init__()
  File "C:\Users\VHcom\Desktop\graph-qt\venv\Lib\site-packages\NodeGraphQt\qgraphics\pipe.py", line 53, in __init__
    self.reset()
  File "C:\Users\VHcom\Desktop\graph-qt\venv\Lib\site-packages\NodeGraphQt\qgraphics\pipe.py", line 471, in reset
    self.set_pipe_styling(color=self.color, width=1.2, style=self.style)
  File "C:\Users\VHcom\Desktop\graph-qt\venv\Lib\site-packages\NodeGraphQt\qgraphics\pipe.py", line 427, in set_pipe_styling
    pen.setWidth(width)
TypeError: setWidth(self, width: int): argument 1 has unexpected type 'float'
`

My environment
Pip list:

`NodeGraphQt   0.6.12
pip           23.2.1
PyQt5         5.15.9
PyQt5-Qt5     5.15.2
PyQt5-sip     12.12.2
Qt.py         1.3.8
setuptools    67.7.0
types-PySide2 5.15.2.1.5
wheel         0.40.0
`
Python version
`python --version
Python 3.11.3                              
`
Machine:
Window OS

**Comment by jchanvfx** [comment]
related to this ticket https://github.com/jchanvfx/NodeGraphQt/issues/384
