### ISSUE TITLE
Error when loading a session

### ISSUE THREAD

**Issue by Gaspounet** [jchanvfx/NodeGraphQt#386]
Hiya!

Using the same command as the one you have under hotkey_functions.py, it fails to connect my nodes together.

I'm using `0.6.25`

Here's the traceback:

```
Traceback (most recent call last):
  File "C:\Users\Gaspounet\AppData\Roaming\Python\Python37\site-packages\NodeGraphQt\base\graph.py", line 1919, in load_session
    self.import_session(file_path, clear_undo_stack=True)
  File "C:\Users\Gaspounet\AppData\Roaming\Python\Python37\site-packages\NodeGraphQt\base\graph.py", line 1946, in import_session
    clear_undo_stack=clear_undo_stack
  File "C:\Users\Gaspounet\AppData\Roaming\Python\Python37\site-packages\NodeGraphQt\base\graph.py", line 1868, in deserialize_session
    self._deserialize(layout_data)
  File "C:\Users\Gaspounet\AppData\Roaming\Python\Python37\site-packages\NodeGraphQt\base\graph.py", line 1822, in _deserialize
    self._undo_stack.push(PortConnectedCmd(in_port, out_port))
TypeError: __init__() missing 1 required positional argument: 'emit_signal'
```

Thanks for your help!

**Comment by jchanvfx** [comment]
Thanks for catching the bugs I've just released a new version 😃.

https://github.com/jchanvfx/NodeGraphQt/releases/tag/v0.6.26

**Comment by Gaspounet** [comment]
Awesome, tested and working!
Glad I could catch these :)
