### ISSUE TITLE
Bug with vertical GroupNode

### ISSUE THREAD

**Issue by AakashTiwari1027** [jchanvfx/NodeGraphQt#413]
When trying to create a GroupNode with NodeGraph.set_layout_direction(1) it throws the following error:

Traceback (most recent call last):
  File "C:\Users\awant\AppData\Local\Programs\Python\Python311\Lib\site-packages\NodeGraphQt\qgraphics\node_base.py", line 197, in paint
    self._paint_vertical(painter, option, widget)
  File "C:\Users\awant\AppData\Local\Programs\Python\Python311\Lib\site-packages\NodeGraphQt\qgraphics\node_group.py", line 125, in _paint_vertical
    painter.setBrush(QtGui.QColor(*self.color).dark(180))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QColor' object has no attribute 'dark'. Did you mean: 'darker'?

Side Note: Would be greatly appreciated if the name of vertical nodes appeared on the node instead of to the right :)

**Comment by EssenOH** [comment]
It might be a no good idea putting the name on the node because there is no an appropriate place.
![image](https://github.com/jchanvfx/NodeGraphQt/assets/3712295/347e9fb0-1886-4edd-8b00-86c88fdba28e)
