### ISSUE TITLE
Not able to import NodeGraphQt, module 'Qt.QtCore' has no attribute 'QSortFilterProxyModel' Error

### ISSUE THREAD

**Issue by SiddhardhaSaran** [jchanvfx/NodeGraphQt#441]
Not sure , what i am doing wrong
I have created a new virtual environment installed pandas, PyQt5, NodeGraphQt 

And when i am trying to do a basic import like this
```

import pandas as pd
from NodeGraphQt import NodeGraph, BaseNode
```
I get this error

```
Traceback (most recent call last):
  File "/Users/bg/VisualAnalysis/initial_test.py", line 2, in <module>
    from NodeGraphQt import NodeGraph, BaseNode
  File "/Users/bg/VisualAnalysis/.venv/lib/python3.12/site-packages/NodeGraphQt/__init__.py", line 64, in <module>
    from .custom_widgets.nodes_palette import NodesPaletteWidget
  File "/Users/bg/VisualAnalysis/.venv/lib/python3.12/site-packages/NodeGraphQt/custom_widgets/nodes_palette.py", line 119, in <module>
    class _NodesGridProxyModel(QtCore.QSortFilterProxyModel):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'Qt.QtCore' has no attribute 'QSortFilterProxyModel'
```

3.12 Python and macos

**Comment by SiddhardhaSaran** [comment]
Install PySide6 worked for me.
`pip install pyside6`
